#!/bin/bash

set -e

OUTDIR=pubmlst
mkdir -p "$OUTDIR"
wget --no-clobber -P "$OUTDIR" http://pubmlst.org/data/dbases.xml 

for URL in $(grep '<url>' $OUTDIR/dbases.xml); do
#  echo $URL
  URL=${URL//<url>}
  URL=${URL//<\/url>}
#  echo ${URL: -4}
  if [ ${URL:(-4)} = ".txt" ]; then
    PROFILE=$(basename $URL .txt)
    echo "# $PROFILE "
    PROFILEDIR="$OUTDIR/$PROFILE"
    eval "mkdir -p '$PROFILEDIR'"
    eval "(cd '$PROFILEDIR' && echo "$URL" && wget -q '$URL')"
  elif [ ${URL:(-4)} = ".tfa" ]; then
    eval "(cd '$PROFILEDIR' && echo "$URL" && wget -q '$URL')"
  fi 
done

# delete fungi schemes
echo rm -frv "$OUTDIR"/{afumigatus,blastocystis,calbicans,cglabrata,ckrusei}
echo rm -frv "$OUTDIR"/{ctropicalis,csinensis,kseptempunctata,sparasitica,tvaginalis}
